### ISSUE TITLE
Cannot import 'RateDecimal'

### ISSUE THREAD

**Issue by sonofevil** [ther0n/beefweb_mpris#6]
Just did a system upgrade and now beefweb_mpris fails to launch.

I tried installing it into a new virtual environment but to no avail.

```
Traceback (most recent call last):
  File "/home/lutra/.local/bin/beefweb_mpris", line 5, in <module>
    from beefweb_mpris.main import main
  File "/home/lutra/.local/venv/lib/python3.12/site-packages/beefweb_mpris/main.py", line 13, in <module>
    from beefweb_mpris.adapter import BeefwebAdapter
  File "/home/lutra/.local/venv/lib/python3.12/site-packages/beefweb_mpris/adapter.py", line 7, in <module>
    from mpris_server.base import Microseconds, PlayState, DbusObj, DEFAULT_RATE, RateDecimal, VolumeDecimal, Track, \
ImportError: cannot import name 'RateDecimal' from 'mpris_server.base' (/home/lutra/.local/venv/lib/python3.12/site-packages/mpris_server/base.py)

```

Running Arch Linux with Python 3.12

**Comment by sonofevil** [comment]
Fixed by updating property names.

https://github.com/ther0n/beefweb_mpris/pull/7
